create table if not exists usr
(
    id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(127),
    password varchar(127),
    role     varchar(127),
    CONSTRAINT uq_username UNIQUE (username)
);
