CREATE TABLE IF NOT EXISTS usr
(
    id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(127),
    password varchar(127),
    role     varchar(127),
    CONSTRAINT uq_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS students
(
    id        int PRIMARY KEY,
    name      varchar(127),
    surname   varchar(127),
    "group"   varchar(127),
    birthdate date
);

select name, surname, group, YEAR(birthdate) as bdate
from students
where YEAR(birthdate) = 1980
